# -*- coding: utf-8 -*-
"""Disaster Insurance Data Analysis Code

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12_1i7RknK44_CP42USe6edVSOWaYwF_E
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

base_path = '/content/drive/MyDrive/Projects | Work | Certifications /Academic Research/'

ins_2020 = pd.read_csv(base_path + 'california_insurance_2020_updated.csv')
ins_2021 = pd.read_csv(base_path + 'california_insurance_2021_updated.csv')
ins_2022 = pd.read_csv(base_path + 'california_insurance_2022_updated.csv')
ins_2023 = pd.read_csv(base_path + 'california_insurance_2023_updated.csv')

fires = pd.read_csv(base_path + 'mapdataall.csv')

fires['incident_dateonly_created'] = pd.to_datetime(fires['incident_dateonly_created'], errors='coerce')
fires_filtered = fires[fires['incident_dateonly_created'].dt.year.between(2020, 2023)].copy()

fires_filtered['year'] = fires_filtered['incident_dateonly_created'].dt.year
fires_grouped = fires_filtered.groupby(['incident_county', 'year']).size().reset_index(name='fire_count')
fires_grouped.rename(columns={'incident_county': 'County'}, inplace=True)

for df, year in zip([ins_2020, ins_2021, ins_2022, ins_2023], [2020, 2021, 2022, 2023]):
    df['Year'] = year
    df['Vol_NonrenewalRate'] = df['Vol_NonrenewalRate'].replace('[%,]', '', regex=True).astype(float) / 100

insurance_all = pd.concat([ins_2020, ins_2021, ins_2022, ins_2023])

merged = pd.merge(insurance_all, fires_grouped, how='left', left_on=['County', 'Year'], right_on=['County', 'year'])
merged['fire_count'] = merged['fire_count'].fillna(0)

corr = merged[['Vol_NonrenewalRate', 'fire_count']].corr()
print(corr)

# Set the figure size
plt.figure(figsize=(16, 12))

# Create a subplot for each year
for i, year in enumerate([2020, 2021, 2022, 2023], 1):
    plt.subplot(2, 2, i)  # 2 rows, 2 columns, position i
    data = merged[merged['Year'] == year]

    sns.scatterplot(data=data, x='fire_count', y='Vol_NonrenewalRate')
    plt.title(f'Fire Count vs. Nonrenewal Rate ({year})')
    plt.xlabel('Number of Fires')
    plt.ylabel('Nonrenewal Rate')
    plt.grid(True)

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
# Assuming 'merged' is your DataFrame

# Set the figure size
plt.figure(figsize=(16, 12))

# Create a subplot for each year
for i, year in enumerate([2020, 2021, 2022, 2023], 1):
    plt.subplot(2, 2, i)  # 2 rows, 2 columns, position i
    data = merged[merged['Year'] == year]

    # Use sns.regplot() instead of sns.scatterplot()
    sns.regplot(data=data, x='fire_count', y='Vol_NonrenewalRate')

    plt.title(f'Fire Count vs. Nonrenewal Rate ({year})')
    plt.xlabel('Number of Fires')
    plt.ylabel('Nonrenewal Rate')
    plt.grid(True)

plt.tight_layout()
plt.show()

for year in [2020, 2021, 2022, 2023]:
    data = merged[merged['Year'] == year]
    corr = data[['fire_count', 'Vol_NonrenewalRate']].corr().iloc[0,1]
    print(f'Correlation for {year}: {corr:.3f}')

# correlation value (r) for each year

import statsmodels.api as sm

for year in [2020, 2021, 2022, 2023]:
    data = merged[merged['Year'] == year].dropna(subset=['fire_count', 'Vol_NonrenewalRate'])

    if data.empty:
        print(f"No data available for year {year} after filtering.")
        continue

    X = data[['fire_count']]
    y = data['Vol_NonrenewalRate']
    X = sm.add_constant(X)

    model = sm.OLS(y, X).fit()

    print(f"\nRegression Results for {year}:")
    print(model.summary())

# from above
#2020 p = 0.075 > 0.05 not statistically significant
#2021 p = 0.017 < 0.05 statistically significant
#2022 p = 0.011 < 0.05 statistically significant
#2023 p = 0.339 > 0.05 not statistically significant